### ISSUE TITLE
Solution to Lab is Missing

### ISSUE THREAD

**Issue by meg-gutshall** [learn-co-students/method-arguments-lab-v-000#1474]
Hello,

I noticed the solutions for this lab is missing. I submitted a pull request to add my solution to the Learn.co solution branch if you want to take a look.

Take care,
Meg Gutshall

**Comment by drakeltheryuujin** [comment]
Hi @meg-gutshall,

Issues with a lesson in the curriculum should be opened on the appropriate
repository in `learn-co-curriculum`. 

When submitting a PR, the `learn-co-curriculum` repositories are reserved for
proposed edits and improvements to the curriculum that will update across all
forks. 

We have updated the materials and believe your issue to have been resolved. 

We apologize for any frustration you might have encountered during this process
but thank you for helping us ensure that others will not encounter the same
problems that you faced.

If you do not believe that this issue has been addressed, please re-open this
issue. Thanks for contributing! 💙
